// App-managed Graphify integration. Project indexes are generated by Graphify's
// deterministic AST pipeline; conversation indexes are generated locally from
// OpenCode history and written in the same NetworkX node-link format.
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::collections::{HashMap, HashSet, VecDeque};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;
use tauri::{AppHandle, Emitter, Manager, State};
use tauri_plugin_shell::process::CommandEvent;
use tauri_plugin_shell::ShellExt;

pub const GRAPHIFY_VERSION: &str = "0.9.39";
const GRAPHIFY_PACKAGE: &str = "graphifyy[mcp,pdf]==0.9.39";
const VERSION_MARKER: &str = ".graphify-version";
const MAX_VIEW_NODES: usize = 700;
const MAX_VIEW_EDGES: usize = 2_000;
const STALL_SECS: u64 = 900;

#[derive(Default)]
pub struct GraphifyState {
    busy: AtomicBool,
}

struct BusyLease<'a>(&'a AtomicBool);

impl Drop for BusyLease<'_> {
    fn drop(&mut self) {
        self.0.store(false, Ordering::Release);
    }
}

impl GraphifyState {
    fn acquire(&self) -> Result<BusyLease<'_>, String> {
        self.busy
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .map_err(|_| "another Graphify operation is already running".to_string())?;
        Ok(BusyLease(&self.busy))
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphifyStatus {
    installed: bool,
    version: &'static str,
    busy: bool,
    mcp_command: Option<String>,
}

#[derive(Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphScopeInfo {
    id: String,
    kind: String,
    title: String,
    indexed_at: u64,
    node_count: usize,
    edge_count: usize,
    graph_path: String,
    project_path: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    source_path: Option<String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConversationMessageInput {
    id: Option<String>,
    role: String,
    #[serde(default)]
    completed: Option<u64>,
    #[serde(default)]
    parts: Vec<Value>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphNodeView {
    id: String,
    label: String,
    node_type: String,
    source_file: Option<String>,
    source_location: Option<String>,
    community: Option<String>,
    community_name: Option<String>,
    role: Option<String>,
    degree: usize,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphEdgeView {
    source: String,
    target: String,
    relation: String,
    confidence: Option<String>,
    confidence_score: Option<f64>,
    source_file: Option<String>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphDocument {
    scope: GraphScopeInfo,
    nodes: Vec<GraphNodeView>,
    edges: Vec<GraphEdgeView>,
    total_nodes: usize,
    total_edges: usize,
    truncated: bool,
}

fn runtime_dir(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(app
        .path()
        .app_data_dir()
        .map_err(|e| e.to_string())?
        .join("runtime")
        .join("graphify-env"))
}

fn data_dir(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(app
        .path()
        .app_data_dir()
        .map_err(|e| e.to_string())?
        .join("graphify"))
}

fn python_bin(app: &AppHandle) -> Result<PathBuf, String> {
    let root = runtime_dir(app)?;
    #[cfg(windows)]
    return Ok(root.join("Scripts").join("python.exe"));
    #[cfg(not(windows))]
    Ok(root.join("bin").join("python"))
}

fn script_bin(app: &AppHandle, name: &str) -> Result<PathBuf, String> {
    let root = runtime_dir(app)?;
    #[cfg(windows)]
    return Ok(root.join("Scripts").join(format!("{name}.exe")));
    #[cfg(not(windows))]
    Ok(root.join("bin").join(name))
}

fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

fn safe_id(id: &str) -> Result<&str, String> {
    if id.is_empty()
        || id.len() > 160
        || !id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_'))
    {
        return Err("invalid graph scope id".into());
    }
    Ok(id)
}

fn scope_root(app: &AppHandle, kind: &str, id: &str) -> Result<PathBuf, String> {
    let folder = match kind {
        "project" => "projects",
        "conversation" => "conversations",
        _ => return Err("invalid graph scope kind".into()),
    };
    Ok(data_dir(app)?.join(folder).join(safe_id(id)?))
}

fn graph_path(root: &Path) -> PathBuf {
    root.join("graphify-out").join("graph.json")
}

fn meta_path(root: &Path) -> PathBuf {
    root.join("scope.json")
}

fn status_of(app: &AppHandle, state: &GraphifyState) -> GraphifyStatus {
    let mcp = script_bin(app, "graphify-mcp").ok().filter(|p| p.exists());
    let graphify = script_bin(app, "graphify").ok().filter(|p| p.exists());
    let version_matches = runtime_dir(app)
        .ok()
        .and_then(|root| std::fs::read_to_string(root.join(VERSION_MARKER)).ok())
        .is_some_and(|version| version.trim() == GRAPHIFY_VERSION);
    let installed = mcp.is_some() && graphify.is_some() && version_matches;
    GraphifyStatus {
        installed,
        version: GRAPHIFY_VERSION,
        busy: state.busy.load(Ordering::Acquire),
        mcp_command: if installed {
            mcp.map(|path| path.to_string_lossy().to_string())
        } else {
            None
        },
    }
}

#[tauri::command]
pub fn graphify_status(app: AppHandle, state: State<'_, GraphifyState>) -> GraphifyStatus {
    status_of(&app, &state)
}

#[tauri::command]
pub async fn setup_graphify(
    app: AppHandle,
    state: State<'_, GraphifyState>,
) -> Result<GraphifyStatus, String> {
    {
        let _lease = state.acquire()?;
        let root = runtime_dir(&app)?;
        std::fs::create_dir_all(&root).map_err(|e| e.to_string())?;
        let python = python_bin(&app)?;
        if !python.exists() {
            crate::uv::create_venv(&app, "graphify", &root).await?;
        }
        crate::uv::run_uv(
            &app,
            "graphify",
            vec![
                "pip".into(),
                "install".into(),
                "--python".into(),
                python.to_string_lossy().to_string(),
                GRAPHIFY_PACKAGE.into(),
            ],
            "uv pip install graphify",
        )
        .await?;
        if !script_bin(&app, "graphify-mcp")?.exists() || !script_bin(&app, "graphify")?.exists() {
            return Err("Graphify installed without its command-line entrypoints".into());
        }
        std::fs::write(root.join(VERSION_MARKER), GRAPHIFY_VERSION).map_err(|e| e.to_string())?;
    }
    let status = status_of(&app, &state);
    Ok(status)
}

async fn run_indexer(app: &AppHandle, source: &Path, output: &Path) -> Result<(), String> {
    let bin = script_bin(app, "graphify")?;
    if !bin.exists() {
        return Err("Graphify is not installed yet".into());
    }
    std::fs::create_dir_all(output).map_err(|e| e.to_string())?;
    let mut cmd = app
        .shell()
        .command(bin.to_string_lossy().to_string())
        .args([
            "extract".to_string(),
            source.to_string_lossy().to_string(),
            "--code-only".to_string(),
            "--no-viz".to_string(),
            "--force".to_string(),
        ])
        .current_dir(source)
        .env("GRAPHIFY_OUT", output.to_string_lossy().to_string());
    for (key, value) in crate::runtime::sidecar_proxy_env(app) {
        cmd = cmd.env(key, value);
    }
    let (mut rx, child) = cmd
        .spawn()
        .map_err(|e| format!("Graphify failed to start: {e}"))?;
    let mut tail = VecDeque::<String>::new();
    loop {
        let event = match tokio::time::timeout(Duration::from_secs(STALL_SECS), rx.recv()).await {
            Err(_) => {
                let _ = child.kill();
                return Err("Graphify produced no output for 15 minutes and was stopped".into());
            }
            Ok(None) => {
                return Err(format!(
                    "Graphify exited without a status: {}",
                    tail.back().cloned().unwrap_or_default()
                ))
            }
            Ok(Some(event)) => event,
        };
        match event {
            CommandEvent::Stdout(bytes) | CommandEvent::Stderr(bytes) => {
                for line in String::from_utf8_lossy(&bytes).split(['\n', '\r']) {
                    let line = line.trim();
                    if line.is_empty() {
                        continue;
                    }
                    if tail.len() == 12 {
                        tail.pop_front();
                    }
                    tail.push_back(line.to_string());
                    let _ = app.emit(
                        "setup-progress",
                        crate::uv::SetupProgress {
                            task: "graphify",
                            line: line.to_string(),
                        },
                    );
                }
            }
            CommandEvent::Error(error) => {
                if tail.len() == 12 {
                    tail.pop_front();
                }
                tail.push_back(error);
            }
            CommandEvent::Terminated(status) => {
                return if status.code == Some(0) {
                    Ok(())
                } else {
                    Err(format!(
                        "Graphify indexing failed: {}",
                        tail.into_iter().collect::<Vec<_>>().join("\n")
                    ))
                };
            }
            _ => {}
        }
    }
}

fn raw_counts(path: &Path) -> Result<(usize, usize), String> {
    let text =
        std::fs::read_to_string(path).map_err(|e| format!("could not read graph.json: {e}"))?;
    let graph: Value =
        serde_json::from_str(&text).map_err(|e| format!("invalid graph.json: {e}"))?;
    let nodes = graph
        .get("nodes")
        .and_then(Value::as_array)
        .map_or(0, Vec::len);
    let edges = graph
        .get("links")
        .or_else(|| graph.get("edges"))
        .and_then(Value::as_array)
        .map_or(0, Vec::len);
    Ok((nodes, edges))
}

fn write_scope(root: &Path, scope: &GraphScopeInfo) -> Result<(), String> {
    std::fs::create_dir_all(root).map_err(|e| e.to_string())?;
    let text = serde_json::to_string_pretty(scope).map_err(|e| e.to_string())?;
    std::fs::write(meta_path(root), text).map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn graphify_index_project(
    app: AppHandle,
    state: State<'_, GraphifyState>,
    project_id: String,
) -> Result<GraphScopeInfo, String> {
    let _lease = state.acquire()?;
    let (title, source) = crate::project::project_source_by_id(&app, safe_id(&project_id)?)?;
    let root = scope_root(&app, "project", &project_id)?;
    let output = root.join("graphify-out");
    run_indexer(&app, &source, &output).await?;
    let graph = graph_path(&root);
    let (node_count, edge_count) = raw_counts(&graph)?;
    let scope = GraphScopeInfo {
        id: project_id,
        kind: "project".into(),
        title,
        indexed_at: now_ms(),
        node_count,
        edge_count,
        graph_path: graph.to_string_lossy().to_string(),
        project_path: root.to_string_lossy().to_string(),
        source_path: Some(crate::artifact_file::native_path(&source)),
    };
    write_scope(&root, &scope)?;
    Ok(scope)
}

fn clipped(text: &str, max_chars: usize) -> String {
    let compact = text.split_whitespace().collect::<Vec<_>>().join(" ");
    let mut chars = compact.chars();
    let out: String = chars.by_ref().take(max_chars).collect();
    if chars.next().is_some() {
        format!("{out}...")
    } else {
        out
    }
}

fn part_text(part: &Value) -> Option<&str> {
    (part.get("type").and_then(Value::as_str) == Some("text"))
        .then(|| part.get("text").and_then(Value::as_str))
        .flatten()
}

fn input_path(part: &Value) -> Option<String> {
    let input = part.get("state")?.get("input")?;
    ["filePath", "path", "file", "target"]
        .iter()
        .find_map(|key| input.get(*key).and_then(Value::as_str))
        .filter(|value| !value.trim().is_empty())
        .map(|value| value.trim().to_string())
}

fn build_conversation_graph(
    session_id: &str,
    title: &str,
    messages: &[ConversationMessageInput],
) -> Value {
    let session_node = format!("conversation:{session_id}");
    let mut nodes = vec![json!({
        "id": session_node,
        "label": title,
        "node_type": "conversation",
        "file_type": "conversation",
        "source_file": format!("session:{session_id}"),
        "source_location": "Conversation",
        "community": 0,
        "community_name": "Conversation"
    })];
    let mut links = Vec::<Value>::new();
    let mut previous_message: Option<String> = None;
    let mut previous_user: Option<String> = None;
    let mut files = HashMap::<String, String>::new();

    for (index, message) in messages.iter().enumerate() {
        let message_id = message
            .id
            .as_deref()
            .filter(|id| !id.is_empty())
            .map(ToOwned::to_owned)
            .unwrap_or_else(|| format!("{index}"));
        let node_id = format!("message:{session_id}:{message_id}");
        let body = message
            .parts
            .iter()
            .filter_map(part_text)
            .collect::<Vec<_>>()
            .join("\n");
        let fallback = if message.role == "user" {
            "User message"
        } else {
            "Assistant response"
        };
        let label = {
            let value = clipped(&body, 120);
            if value.is_empty() {
                fallback.to_string()
            } else {
                value
            }
        };
        let community = if message.role == "user" { 1 } else { 2 };
        nodes.push(json!({
            "id": node_id,
            "label": label,
            "node_type": "message",
            "file_type": "conversation",
            "role": message.role,
            "text": clipped(&body, 1200),
            "completed": message.completed,
            "source_file": format!("session:{session_id}"),
            "source_location": format!("Turn {}", index + 1),
            "community": community,
            "community_name": if message.role == "user" { "Questions" } else { "Responses" }
        }));
        links.push(edge(&session_node, &node_id, "contains"));
        if let Some(previous) = previous_message.as_ref() {
            links.push(edge(previous, &node_id, "followed_by"));
        }
        if message.role == "assistant" {
            if let Some(user) = previous_user.take() {
                links.push(edge(&user, &node_id, "answered_by"));
            }
        } else if message.role == "user" {
            previous_user = Some(node_id.clone());
        }

        for (part_index, part) in message.parts.iter().enumerate() {
            if part.get("type").and_then(Value::as_str) != Some("tool") {
                continue;
            }
            let tool = part.get("tool").and_then(Value::as_str).unwrap_or("tool");
            let tool_title = part
                .get("state")
                .and_then(|state| state.get("title"))
                .and_then(Value::as_str)
                .unwrap_or(tool);
            let tool_id = format!("tool:{session_id}:{message_id}:{part_index}");
            nodes.push(json!({
                "id": tool_id,
                "label": clipped(tool_title, 120),
                "node_type": "tool",
                "file_type": "conversation",
                "tool": tool,
                "source_file": format!("session:{session_id}"),
                "source_location": format!("Turn {}", index + 1),
                "community": 3,
                "community_name": "Tools"
            }));
            links.push(edge(&node_id, &tool_id, "used_tool"));
            if let Some(path) = input_path(part) {
                let file_id = if let Some(existing) = files.get(&path) {
                    existing.clone()
                } else {
                    let id = format!("file:{session_id}:{}", files.len());
                    files.insert(path.clone(), id.clone());
                    nodes.push(json!({
                        "id": id,
                        "label": path,
                        "node_type": "file",
                        "file_type": "file",
                        "source_file": format!("session:{session_id}"),
                        "community": 4,
                        "community_name": "Files"
                    }));
                    id
                };
                links.push(edge(&tool_id, &file_id, "accessed"));
            }
        }
        previous_message = Some(node_id);
    }
    json!({
        "directed": true,
        "multigraph": false,
        "graph": { "scope_kind": "conversation", "session_id": session_id },
        "nodes": nodes,
        "links": links
    })
}

fn edge(source: &str, target: &str, relation: &str) -> Value {
    json!({
        "source": source,
        "target": target,
        "_src": source,
        "_tgt": target,
        "relation": relation,
        "confidence": "EXTRACTED",
        "confidence_score": 1.0
    })
}

#[tauri::command]
pub fn graphify_index_conversation(
    app: AppHandle,
    state: State<'_, GraphifyState>,
    session_id: String,
    title: String,
    messages: Vec<ConversationMessageInput>,
) -> Result<GraphScopeInfo, String> {
    let _lease = state.acquire()?;
    safe_id(&session_id)?;
    let title = title.trim();
    if title.is_empty() {
        return Err("conversation title is empty".into());
    }
    let root = scope_root(&app, "conversation", &session_id)?;
    let path = graph_path(&root);
    std::fs::create_dir_all(path.parent().ok_or("invalid graph path")?)
        .map_err(|e| e.to_string())?;
    let graph = build_conversation_graph(&session_id, title, &messages);
    let text = serde_json::to_string_pretty(&graph).map_err(|e| e.to_string())?;
    std::fs::write(&path, text).map_err(|e| e.to_string())?;
    let (node_count, edge_count) = raw_counts(&path)?;
    let scope = GraphScopeInfo {
        id: session_id,
        kind: "conversation".into(),
        title: title.to_string(),
        indexed_at: now_ms(),
        node_count,
        edge_count,
        graph_path: path.to_string_lossy().to_string(),
        project_path: root.to_string_lossy().to_string(),
        source_path: None,
    };
    write_scope(&root, &scope)?;
    Ok(scope)
}

fn read_scope(root: &Path) -> Option<GraphScopeInfo> {
    let text = std::fs::read_to_string(meta_path(root)).ok()?;
    let scope: GraphScopeInfo = serde_json::from_str(&text).ok()?;
    Path::new(&scope.graph_path).is_file().then_some(scope)
}

#[tauri::command(async)]
pub fn graphify_list_scopes(app: AppHandle) -> Result<Vec<GraphScopeInfo>, String> {
    let root = data_dir(&app)?;
    let mut scopes = Vec::new();
    for kind in ["projects", "conversations"] {
        let Ok(entries) = std::fs::read_dir(root.join(kind)) else {
            continue;
        };
        for entry in entries.flatten() {
            if entry.file_type().map(|f| f.is_dir()).unwrap_or(false) {
                if let Some(scope) = read_scope(&entry.path()) {
                    scopes.push(scope);
                }
            }
        }
    }
    scopes.sort_by(|a, b| b.indexed_at.cmp(&a.indexed_at));
    Ok(scopes)
}

fn value_string(value: Option<&Value>) -> Option<String> {
    match value {
        Some(Value::String(value)) => Some(value.clone()),
        Some(Value::Number(value)) => Some(value.to_string()),
        _ => None,
    }
}

fn graph_document(scope: GraphScopeInfo) -> Result<GraphDocument, String> {
    let text = std::fs::read_to_string(&scope.graph_path)
        .map_err(|e| format!("could not read graph.json: {e}"))?;
    let raw: Value = serde_json::from_str(&text).map_err(|e| format!("invalid graph.json: {e}"))?;
    let raw_nodes = raw
        .get("nodes")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let raw_edges = raw
        .get("links")
        .or_else(|| raw.get("edges"))
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let mut degrees = HashMap::<String, usize>::new();
    for edge in &raw_edges {
        if let Some(source) = value_string(edge.get("source")) {
            *degrees.entry(source).or_default() += 1;
        }
        if let Some(target) = value_string(edge.get("target")) {
            *degrees.entry(target).or_default() += 1;
        }
    }
    let mut ranked = raw_nodes;
    ranked.sort_by(|a, b| {
        let aid = value_string(a.get("id")).unwrap_or_default();
        let bid = value_string(b.get("id")).unwrap_or_default();
        degrees
            .get(&bid)
            .unwrap_or(&0)
            .cmp(degrees.get(&aid).unwrap_or(&0))
    });
    let total_nodes = ranked.len();
    let total_edges = raw_edges.len();
    ranked.truncate(MAX_VIEW_NODES);
    let selected: HashSet<String> = ranked
        .iter()
        .filter_map(|node| value_string(node.get("id")))
        .collect();
    let nodes = ranked
        .into_iter()
        .filter_map(|node| {
            let id = value_string(node.get("id"))?;
            let label = value_string(node.get("label")).unwrap_or_else(|| id.clone());
            let community = value_string(node.get("community"));
            let community_name = value_string(node.get("community_name"))
                .or_else(|| community.as_ref().map(|value| format!("Community {value}")));
            let node_type = value_string(node.get("node_type"))
                .or_else(|| value_string(node.get("file_type")))
                .or_else(|| value_string(node.get("type")))
                .unwrap_or_else(|| "concept".into());
            Some(GraphNodeView {
                degree: *degrees.get(&id).unwrap_or(&0),
                id,
                label,
                node_type,
                source_file: value_string(node.get("source_file")),
                source_location: value_string(node.get("source_location")),
                community,
                community_name,
                role: value_string(node.get("role")),
            })
        })
        .collect::<Vec<_>>();
    let edges = raw_edges
        .into_iter()
        .filter_map(|edge| {
            let source = value_string(edge.get("source"))?;
            let target = value_string(edge.get("target"))?;
            if !selected.contains(&source) || !selected.contains(&target) {
                return None;
            }
            Some(GraphEdgeView {
                source,
                target,
                relation: value_string(edge.get("relation")).unwrap_or_else(|| "related".into()),
                confidence: value_string(edge.get("confidence")),
                confidence_score: edge.get("confidence_score").and_then(Value::as_f64),
                source_file: value_string(edge.get("source_file")),
            })
        })
        .take(MAX_VIEW_EDGES)
        .collect::<Vec<_>>();
    Ok(GraphDocument {
        scope,
        nodes,
        edges,
        total_nodes,
        total_edges,
        truncated: total_nodes > MAX_VIEW_NODES || total_edges > MAX_VIEW_EDGES,
    })
}

#[tauri::command(async)]
pub fn graphify_read_graph(
    app: AppHandle,
    kind: String,
    id: String,
) -> Result<GraphDocument, String> {
    let root = scope_root(&app, &kind, &id)?;
    let scope = read_scope(&root).ok_or("graph has not been indexed")?;
    graph_document(scope)
}

#[tauri::command(async)]
pub fn graphify_open_source(
    app: AppHandle,
    project_id: String,
    source_file: String,
) -> Result<(), String> {
    let (_, root) = crate::project::project_source_by_id(&app, safe_id(&project_id)?)?;
    let candidate = Path::new(&source_file);
    let joined = if candidate.is_absolute() {
        candidate.to_path_buf()
    } else {
        root.join(candidate)
    };
    let canonical = joined
        .canonicalize()
        .map_err(|e| format!("source file is unavailable: {e}"))?;
    if !canonical.starts_with(&root) || !canonical.is_file() {
        return Err("source file is outside the indexed project".into());
    }
    crate::artifact_file::os_open(&canonical)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn conversation_graph_preserves_turn_tool_and_file_relationships() {
        let messages = vec![
            ConversationMessageInput {
                id: Some("u1".into()),
                role: "user".into(),
                completed: Some(1),
                parts: vec![json!({"type":"text","text":"Inspect the model"})],
            },
            ConversationMessageInput {
                id: Some("a1".into()),
                role: "assistant".into(),
                completed: Some(2),
                parts: vec![
                    json!({"type":"text","text":"The parser owns this."}),
                    json!({"type":"tool","tool":"read","state":{"title":"Read parser.rs","input":{"filePath":"src/parser.rs"}}}),
                ],
            },
        ];
        let graph = build_conversation_graph("ses_1", "Parser review", &messages);
        let nodes = graph["nodes"].as_array().unwrap();
        let links = graph["links"].as_array().unwrap();
        assert_eq!(nodes.len(), 5);
        assert!(links.iter().any(|edge| edge["relation"] == "answered_by"));
        assert!(links.iter().any(|edge| edge["relation"] == "accessed"));
        assert!(nodes.iter().any(|node| node["label"] == "src/parser.rs"));
    }

    #[test]
    fn scope_ids_are_one_safe_path_segment() {
        assert_eq!(safe_id("ses_abc-123").unwrap(), "ses_abc-123");
        assert!(safe_id("../escape").is_err());
        assert!(safe_id("").is_err());
    }

    #[test]
    fn graph_document_exposes_numbered_communities() {
        let root = std::env::temp_dir().join(format!(
            "nebulamat-graphify-test-{}-{}",
            std::process::id(),
            now_ms()
        ));
        std::fs::create_dir_all(&root).unwrap();
        let path = root.join("graph.json");
        std::fs::write(
            &path,
            serde_json::to_vec(&json!({
                "nodes": [{"id": "parser", "label": "Parser", "community": 3}],
                "links": []
            }))
            .unwrap(),
        )
        .unwrap();
        let scope = GraphScopeInfo {
            id: "project_1".into(),
            kind: "project".into(),
            title: "Parser".into(),
            indexed_at: now_ms(),
            node_count: 1,
            edge_count: 0,
            graph_path: path.to_string_lossy().into_owned(),
            project_path: root.to_string_lossy().into_owned(),
            source_path: None,
        };

        let document = graph_document(scope).unwrap();
        assert_eq!(document.nodes[0].community.as_deref(), Some("3"));
        assert_eq!(
            document.nodes[0].community_name.as_deref(),
            Some("Community 3")
        );
        std::fs::remove_dir_all(root).unwrap();
    }
}
